[package]
name = "materials"
version = "0.0.0"
edition = "2021"
authors = ["AlexeyPe<alexey_pe@ro.ru>"]
description = "Data on rocks, ores, minerals, etc."
keywords = ["data"]
license = "MIT"

[dependencies]
